[tool.pyright]

include = [
    "gym/version.py",
    "gym/logger.py",
    "gym/envs/registration.py",
    "gym/spaces/space.py",
    "gym/core.py",
    "gym/utils/seeding.py"
]
exclude = [
    "**/node_modules",
    "**/__pycache__",
]
strict = ["gym/version.py", "gym/logger.py"]

reportMissingImports = true
reportMissingTypeStubs = false
verboseOutput = true
